spring.application.name = aceprep

spring.datasource.url=jdbc:postgresql://localhost:5432/ace_prep
spring.datasource.username = likhilkosuru
spring.datasource.password = Likhil$1209

spring.jpa.hibernate.ddl-auto= update
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql = true

#jwt
jwt.secret=mysecretkeymysecretkeymysecretkey
jwt.expiration=3600000