spring.application.name = aceprep

spring.datasource.url = jdbc:postgresql://localhost:5432/aceprep
spring.datasource.username = postgres
spring.datasource.password = Likhil$1209

spring.jpa.ddl-auto= update
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql = true